version: '3.3'

services:
  app:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    volumes:
      - type: bind
        source: ./cookies.txt
        target: /app/cookies.txt
